### ISSUE TITLE
Can't resolve 'pdfjs-dist/es5/build/pdf'

### ISSUE THREAD

**Issue by FraCart** [lublak/pdfdataextract#2]
**Describe the bug**
When starting the app it just doesn't compile. I've already added 'pdfjs-dist' to my package.json.
Module not found: Can't resolve 'pdfjs-dist/es5/build/pdf' in '/path/to/project/node_modules/pdfdataextract/dist'

**Expected behavior**
Compiles.

**Environment (please complete the following information):**
 - OS: Linux
 - Node.js Version 15.14.0

**Additional context**
I've installed the package with yarn add.

**Comment by lublak** [comment]
@FraCart Thank you for reporting this.
There is a new pdf-dist minor release version that is not compatible with the old release. I have adapted the code and it should now work. https://github.com/lublak/pdfdataextract/commit/08dcecc247dcf9fbc637e113e9192330c1808b7c
The new version should also appear shortly on npm with version v3.0.0.
If the problem is not solved, please contact me again.
