### ISSUE TITLE
Right-hand side of 'instanceof' is not an object 

### ISSUE THREAD

**Issue by Tejas239725** [lublak/pdfdataextract#4]
**Describe the bug**
Trying Extract pdf outlines or table of contents but getting " Right-hand side of 'instanceof' is not an object " error after trying to extract data from pdf in server.  

**Expected behavior**
Need to extract Outlines of PDF

**Environment (please complete the following information):**
 - Node.js Version v12.18.4
 - NPM Version 6.14.6
 - OS Ubuntu 18.04.5 LTS
![pdfdataextractissue](https://user-images.githubusercontent.com/66859696/126033285-3b6dd390-cfb2-4a14-bd7f-f31f41204461.png)

**Comment by lublak** [comment]
Hi @Tejas239725,

thank you for your bug report.
First question: Is your pdf file pubic so I can test it?
Second question: Is it possible that I can use it in my test cases and publish it to GitHub?

**Comment by Tejas239725** [comment]
PDF Iink: https://drive.google.com/file/d/1z9icbCvgnvTeFBgv29iGuQRdhzheYd-0/view?usp=sharing

I didn`t got your second questions.

**Comment by lublak** [comment]
The second question is whether I can upload this PDF file to github to include it in my tests.
pdfdataextract is tested with every change so that I can make sure that I have made all the changes so that the old stuff can be read correctly.

**Comment by lublak** [comment]
So i checked it with:

```ts
const PDF_TEST_FILE = './test/material.pdf';
const buffer = readFileSync(PDF_TEST_FILE);
const extractor = await PdfDataExtractor.get(buffer, {
	verbosity: VerbosityLevel.ERRORS,
});
const outline = await extractor.getOutline();
```

outline data:
```
[ PageNumberOutline { title: 'References', page: 0, childs: [] } ]
```
and it works fine. Also on v12.18.4
The only instanceof in my code is located here:
https://github.com/lublak/pdfdataextract/blob/main/src/pdfdataextractor.ts#L77

are there any special features on your site that call for an instanceof?

**Comment by Tejas239725** [comment]
Only First Time working Properly but after next try it throws error         
 const pdfFile = req.files[0].buffer; // these is buffer of pdf
  const extractor = await PdfDataExtractor.get(pdfFile, { verbosity: VerbosityLevel.ERRORS });
 const outlines = await extractor.getOutline();
  
![issue2](https://user-images.githubusercontent.com/66859696/126164361-e8cd879d-befa-441f-b094-266ca3477d60.png)
console.log(outlines);

**Comment by Tejas239725** [comment]
Before these method we are not using any method or library but after extraction using libraries

**Comment by lublak** [comment]
@Tejas239725 thanks for your response.
Its look like the exception comes from pdfjs.
However, the line that is affected does not show any error:
![grafik](https://user-images.githubusercontent.com/44057030/126190202-723062c5-1e56-4cd9-8156-07e59b016464.png)
![grafik](https://user-images.githubusercontent.com/44057030/126190366-f76496e5-d7bd-4bbd-ac07-051e36ded284.png)

I also tried with a clean project on an Ubuntu in a VM with nodejs v12.18.4 and it works fine.
Can you please try to introduce nodejs manuall (with the command "node")
And then simply enter "URL" there. Then [class URL] should be the result if your installation is OK.

I assume that you use express in your project. Which library do you use for the multipart besides express?

**Comment by Tejas239725** [comment]
![improper installation](https://user-images.githubusercontent.com/66859696/126293517-cf568ef9-743a-4cb2-9981-972691cbf884.png)
Getting these while checking URL. What is problem and how to solve?

**Comment by lublak** [comment]
No it looks fine.
I was just checking if the object URL exists and it is an object.
It would have given a "Right-hand side of 'instanceof' is not an object" error if it had been incorrect.
Since the error is really strange and occurs on a line that just doesn't have an error, I just wanted to check it. 
It's also hard for me to figure out what's wrong with you since it's not really a problem on my side with the code or in pdfjs.
Therefore it would be important to know in which environment you have installed it and how exactly your code looks like in this area so that I can look into it if I notice something.
Do you use the expressjs web framework? And you have a form that accepts the file?
Which library do you use besides express to accept the files?
Do you use something completely different? A ready-made system? If so which one? And where do you put the source code?

**Comment by Tejas239725** [comment]
Yes i am using express framework. And using multer , AWS s3 to Store files.  Using Angular 8 for Frontend Forms.

**Comment by lublak** [comment]
@Tejas239725 sorry for the delay.

I created a complete example with express, multer and pdfdataextract. It works fine:

```js
var express = require('express')
var multer  = require('multer')
var upload = multer()
var pdfdataextract = require('pdfdataextract');
var PdfDataExtractor = pdfdataextract.PdfDataExtractor;
var VerbosityLevel = pdfdataextract.VerbosityLevel;

var app = express()

app.get('/', function (req, res, next) {
  res.send(`
    <form action="/test" method="post" enctype="multipart/form-data">
      <input type="file" name="test" />
      <button>Submit</button>
    </form>
  `);
})

app.post('/test', upload.single('test'), async function (req, res, next) {
  const pdfFile = req.file.buffer.buffer; // these is buffer of pdf
  const extractor = await PdfDataExtractor.get(pdfFile, { verbosity: VerbosityLevel.ERRORS });
  const outlines = await extractor.getOutline();
  res.send(JSON.stringify(outlines));
})

app.listen(5000, () => {
  console.log(`Example app listening at http://localhost:${5000}`)
})
```

Keep in mind:
- use async keywords, if you use await.
- if you use a destination folder in multer (`multer({ dest: 'uploads/' })`) than you need read your file (buffer is empty)

I close it now because as I currently assume that the error is not on my side.
If you have any further questions, please do not hesitate to contact me.
